.\" Manpage for mstatus.
.\" Contact dv15lgr@cs.umu.se to correct errors or typos.
.TH man 1 "13 September 2016" "1.0" "mstatus man page"
.SH NAME
mstatus \- add an entry to the users .plan file
.SH SYNOPSIS
mstatus {login|logout|xlock|unexlock} [message]
.SH DESCRIPTION
mstatus is a script to add a message to the .plan file of the current user.
.SH OPTIONS
The action login, logout, xlock or unexlock is a mandatory argument to mstatus. All further arguments are interpreted as text message to be added to .plan.
.SH SEE ALSO
finger(8)
.SH AUTHOR
Lorenz Gerber (dv15lgr@cs.umu.se)